### ISSUE TITLE
Help with installation?

### ISSUE THREAD

**Issue by sousanunes** [InsightSoftwareConsortium/ITKColorNormalization#41] opened 2022-12-21 18:31 UTC
Hi!

I installed itk-spcn using pip, within a conda env with python=3.9.

However, when using the itk within the same environment, it does not work properly. I manage to import and read/write images. 

But when calling itk.structure_preserving_color_normalization_filter(). I get
AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid

I get a similar outcome when trying itk.StructurePreservingColorNormalizationFilter.New()

There seems to be a problem with the installation of the python interface. I've wrapped my head around it and spent hours searching but can't figure out why this is happening. Any help would be greatly appreciated! Thank you!

**Comment by dzenanz** [comment] 2022-12-21 20:01
This is a duplicate of https://github.com/InsightSoftwareConsortium/ITK/issues/3528. This package needs new wheels. @tbirdso or @Leengit might make them?

**Comment by tbirdso** [comment] 2022-12-22 15:41
@dzenanz @Leengit I have opened #42 to build ITKColorNormalization wheels for v5.3.0. This issue should be addressed once those changes are merged and a new release is tagged.

@sousanunes Thank you for bringing this to our attention! We will have an updated release on PyPI soon that you will be able to `pip install` to resolve the issue. If you have other questions about using ITK and modules like ITKColorNormalization feel free to ask them on the [ITK community forum](https://discourse.itk.org/).

**Comment by sousanunes** [comment] 2022-12-22 18:01
Thanks so much!

**Closed as completed** 2022-12-30 16:38 UTC

**Comment by tbirdso** [comment] 2023-01-02 14:05
Hi @sousanunes , updated packages are now available for download, thank you for your patience.

```bash
python -m pip install itk==v5.3.0 itk-spcn==v0.2.0
```

Please let us know if you run into any additional issues.
